import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    stock: 'Stock',
    inventory: 'Inventory',
    clients: 'Clients',
    employers: 'Employers',
    expenses: 'Expenses',
    reports: 'Reports',
    suppliers: 'Suppliers',
    settings: 'Settings',
    mainMenu: 'Main Menu',

    // Dashboard
    welcomeBack: "Welcome back! Here's what's happening with your business.",
    monthRevenue: 'Month Revenue',
    monthExpenses: 'Month Expenses',
    netProfit: 'Net Profit',
    stockValue: 'Stock Value',
    production: 'Production',
    receivable: 'Receivable',
    payable: 'Payable',
    pendingPayroll: 'Pending Payroll',
    salesThisMonth: 'sales this month',
    expensesCount: 'expenses',
    thisMonth: 'This month',
    itemsInStock: 'items in stock',
    batchesThisMonth: 'batches this month',
    fromClients: 'From clients',
    toSuppliers: 'To suppliers',
    pending: 'pending',
    alertsNotifications: 'Alerts & Notifications',
    lowStockAlert: 'Low Stock Alert',
    itemsBelowMin: 'items are below minimum stock level',
    viewDetails: 'View Details',
    pendingPayrollAlert: 'Pending Payroll',
    salaryPaymentsPending: 'salary payments pending',
    processPayroll: 'Process Payroll',
    outstandingPayments: 'Outstanding Payments',
    pendingFromClients: 'pending from clients',
    viewClients: 'View Clients',
    allGood: 'All Good!',
    noAlerts: 'No critical alerts. Your business is running smoothly.',
    refresh: 'Refresh',

    // Stock
    stockManagement: 'Stock Management',
    trackRawMaterials: 'Manage your raw materials and ingredients',
    addStock: 'Add Stock',
    search: 'Search',
    searchStock: 'Search stock...',
    allCategories: 'All Categories',
    lowStockOnly: 'Low Stock Only',
    totalItems: 'Total Items',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    lowStockAlerts: 'Low Stock Alerts',
    totalValue: 'Total Value',
    noStockItems: 'No stock items yet',
    noMatchingItems: 'No matching items',
    addFirstStock: 'Get started by adding your first stock item',
    tryAdjustingFilters: 'Try adjusting your filters',
    addStockItem: 'Add Stock Item',
    item: 'Item',
    unitCost: 'Unit Cost',
    value: 'Value',
    ok: 'OK',
    low: 'Low',
    deleteItem: 'Delete Item?',
    cannotBeUndone: 'This action cannot be undone.',
    areYouSureDelete: 'Are you sure you want to delete',
    removeStock: 'Remove Stock',
    current: 'Current',
    quantityTo: 'Quantity to',
    reasonForAdjustment: 'Reason for adjustment',

    // Common
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    actions: 'Actions',
    name: 'Name',
    description: 'Description',
    quantity: 'Quantity',
    unit: 'Unit',
    price: 'Price',
    cost: 'Cost',
    total: 'Total',
    date: 'Date',
    status: 'Status',
    notes: 'Notes',
    phone: 'Phone',
    address: 'Address',
    email: 'Email',
    balance: 'Balance',
    category: 'Category',
    from: 'From',
    uncategorized: 'Uncategorized',
    remove: 'Remove',
    items: 'items',
    orders: 'orders',
    clear: 'Clear',

    // Products/Inventory
    products: 'Products',
    createProduct: 'Create Product',
    productName: 'Product Name',
    sellingPrice: 'Selling Price',
    recipe: 'Recipe',
    ingredients: 'Ingredients',
    productionBatches: 'Production Batches',
    startProduction: 'Start Production',
    inventoryProduction: 'Inventory / Production',
    createProductsAndManage: 'Create products and manage production batches',
    totalProducts: 'Total Products',
    unitsProduced: 'units produced',
    productionCost: 'Production Cost',
    productionHistory: 'Production History',
    searchProducts: 'Search products...',
    searchProductionBatches: 'Search production batches...',
    noProductsYet: 'No products yet',
    noProductsMatch: 'No products match your search',
    createFirstProduct: 'Create your first product to start production',
    tryDifferentSearch: 'Try a different search term',
    totalProduced: 'Total Produced',
    noBatchesYet: 'No production history yet',
    noBatchesMatch: 'No batches match your search',
    startProducingToSee: 'Start producing to see history here',
    quantityToProduce: 'Quantity to Produce',
    numberOfUnits: 'Number of',
    expenseAllocation: 'Expense Allocation (DZD)',
    expenseAllocationHint: 'e.g., electricity, labor costs',
    productionDate: 'Production Date',
    productionNotes: 'Production notes...',
    deleteProduct: 'Delete Product',
    deleteProductWarning: 'This will delete all recipes and batches',

    // Clients
    clientManagement: 'Client Management',
    manageClients: 'Manage your customer database and sales',
    addClient: 'Add Client',
    searchClients: 'Search clients...',
    totalClients: 'Total Clients',
    allClientCategories: 'All Client Categories',
    clientCategory: 'Client Category',
    noCategory: 'No Category',
    selectClientCategory: 'Select client category...',
    createNewCategory: 'Create New Category',
    newCategoryName: 'New category name',
    categoryNameRequired: 'Category name is required',
    withDebt: 'With Debt',
    totalSales: 'Total Sales',
    totalRevenue: 'Total Revenue',
    outstanding: 'Outstanding',
    noClientsYet: 'No clients yet',
    startAddingCustomers: 'Start adding your customers to the database',
    addFirstClient: 'Add First Client',
    viewSales: 'View Sales',
    showingSalesFor: 'Showing sales for:',
    allStatus: 'All Status',
    searchSales: 'Search sales...',
    noSalesYet: 'No sales yet',
    startRecordingSales: 'Start recording sales to track revenue',
    createFirstSale: 'Create First Sale',
    addPayment: 'Add Payment',
    client: 'Client',
    alreadyPaid: 'Already Paid',
    remaining: 'Remaining',
    paymentAmount: 'Payment Amount (DZD)',
    enterAmount: 'Enter amount...',
    recordPayment: 'Record Payment',
    totalPurchases: 'Total Purchases',

    // Sales
    sales: 'Sales',
    newSale: 'New Sale',
    saleItems: 'Sale Items',
    paid: 'Paid',
    partial: 'Partial',
    unpaid: 'Unpaid',

    // Expenses
    expenseManagement: 'Expense Management',
    trackExpenses: 'Track and manage all business expenses',
    addExpense: 'Add Expense',
    totalExpenses: 'Total Expenses',
    averageExpense: 'Average Expense',
    categories: 'Categories',
    searchExpenses: 'Search expenses...',
    recurring: 'Recurring',
    noExpensesYet: 'No expenses recorded',
    noExpensesMatch: 'No expenses match your filters',
    startTrackingExpenses: 'Start tracking your business expenses',
    tryAdjustingSearch: 'Try adjusting your search or filters',
    recordExpense: 'Record Expense',
    deleteExpense: 'Delete Expense',

    // Employers
    employerManagement: 'Employer Management',
    manageEmployees: 'Manage your team and payroll',
    addEmployer: 'Add Employee',
    salary: 'Salary',
    role: 'Role',
    payroll: 'Payroll',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    monthlySalaries: 'Monthly Salaries',
    pendingPayments: 'Pending Payments',
    employees: 'Employees',
    searchEmployees: 'Search employees...',
    searchPayroll: 'Search payroll...',
    activeOnly: 'Active Only',
    noEmployeesYet: 'No employees yet',
    addTeamMembers: 'Add your team members to manage payroll',
    addFirstEmployee: 'Add First Employee',
    noPayrollRecords: 'No payroll records',
    generatePayrollForEmployees: 'Generate payroll for your employees',
    generatePayroll: 'Generate Payroll',
    period: 'Period',
    employee: 'Employee',
    amount: 'Amount',
    markAsPaid: 'Mark as Paid',
    generate: 'Generate',
    generatePayrollDescription: 'This will create payroll records for all active employees for the selected month.',
    year: 'Year',
    month: 'Month',
    skipExistingPayroll: 'This will skip employees who already have payroll for this month.',
    hired: 'Hired',
    monthlySalary: 'Monthly Salary',
    noRoleAssigned: 'No role assigned',
    active: 'active',
    inactive: 'inactive',

    // Suppliers
    supplierManagement: 'Supplier Management',
    manageSuppliers: 'Manage your supplier network and purchases',
    addSupplier: 'Add Supplier',
    totalSuppliers: 'Total Suppliers',
    totalPurchasesAmount: 'Total Purchases',
    outstandingDebt: 'Outstanding Debt',
    searchSuppliers: 'Search suppliers...',
    noSuppliersYet: 'No suppliers yet',
    noSuppliersMatch: 'No suppliers match your filters',
    addSuppliersToManage: 'Add your suppliers to manage orders and inventory',
    addFirstSupplier: 'Add First Supplier',
    deleteSupplier: 'Delete Supplier',
    deleteSupplierWarning: 'This will also delete all purchases',
    purchases: 'purchases',

    // Reports
    reportsAnalytics: 'Reports & Analytics',
    viewReports: 'Business analytics and performance insights',
    profitLoss: 'Profit & Loss',
    stockAlerts: 'Stock Alerts',
    monthProfit: 'Month Profit',
    receivableClients: 'Receivable (Clients)',
    payableSuppliers: 'Payable (Suppliers)',
    lowStockItems: 'Low Stock Items',
    monthProduction: 'Month Production',
    batches: 'batches',
    collectedThisMonth: 'Collected This Month',
    to: 'to',
    revenue: 'Revenue',
    productionCosts: 'Production Costs',
    margin: 'margin',
    monthlyProfitLoss: 'Monthly Profit/Loss',
    profit: 'Profit',
    stockByCategory: 'Stock by Category',
    noLowStockItems: 'No low stock items',
    minimum: 'Minimum',
    shortage: 'Shortage',
    supplier: 'Supplier',
    topProducts: 'Top Products',
    noSalesData: 'No sales data',
    unitsSold: 'units sold',
    salesByClient: 'Sales by Client',
    noClientData: 'No client data',
    owes: 'Owes',
    monthlySales: 'Monthly Sales',
    collected: 'Collected',
    expensesByCategory: 'Expenses by Category',
    monthlyExpenses: 'Monthly Expenses',
    count: 'Count',
    productionByProduct: 'Production by Product',
    noProductionData: 'No production data',
    avgUnitCost: 'Avg Unit Cost',
    recentProductionHistory: 'Recent Production History',
    noProductionHistory: 'No production history',
    totalAmount: 'Total Amount',
    totalCost: 'Total Cost',
    product: 'Product',
    businessAnalytics: 'Business analytics and performance insights',

    // Confirm dialogs
    confirmDeleteClient: 'Are you sure? This will also delete all sales for this client.',
    confirmDeleteSale: 'Are you sure you want to delete this sale?',
    confirmDeleteEmployee: 'Are you sure? This will also delete all payroll records for this employee.',
    confirmDeletePayroll: 'Are you sure you want to delete this payroll record?',
    willDeletePurchases: 'This will also delete all purchases',

    // Modal titles
    editStockItem: 'Edit Stock Item',
    editClient: 'Edit Client',
    addNewClient: 'Add New Client',
    editSupplier: 'Edit Supplier',
    editEmployee: 'Edit Employee',
    addNewEmployee: 'Add New Employee',
    editExpense: 'Edit Expense',
    editSale: 'Edit Sale',
    editProduct: 'Edit Product',
    createProductTitle: 'Create Product',

    // Form labels
    itemName: 'Item Name',
    selectCategory: 'Select category',
    selectSupplier: 'Select supplier (optional)',
    currentQuantity: 'Current Quantity',
    initialQuantity: 'Initial Quantity',
    costPerUnit: 'Cost per Unit (DZD)',
    lowStockAlertThreshold: 'Low Stock Alert Threshold',
    alertWhenBelow: 'Alert when quantity falls below this',
    useStockAdjustments: 'Use stock adjustments to change quantity',
    additionalNotes: 'Additional notes...',
    update: 'Update',
    clientName: 'Client Name',
    optional: 'optional',
    initialBalance: 'Initial Balance (DZD)',
    amountOwed: 'Amount owed by client',
    selectClient: 'Select a client',
    saleDate: 'Sale Date',
    selectProduct: 'Select product',
    qty: 'Qty',
    addItem: 'Add Item',
    summary: 'Summary',
    subtotal: 'Subtotal',
    paidAmount: 'Paid Amount',
    amountPaidNow: 'Amount paid now',
    createSale: 'Create Sale',
    hireDate: 'Hire Date',
    monthlySalaryAmount: 'Monthly Salary (DZD)',
    employeeIsActive: 'Employee is active',
    expenseCategory: 'Expense Category',
    expenseAmount: 'Amount (DZD)',
    expenseDate: 'Date',
    isRecurring: 'This is a recurring expense',
    recurringPeriod: 'Recurring Period',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    manualCostPerUnit: 'Manual Cost per Unit (DZD)',
    overrideRecipeCost: 'Override recipe cost calculation',
    recipeIngredients: 'Recipe / Ingredients',
    ingredientsList: 'Define ingredients needed per unit',
    selectIngredient: 'Select ingredient',
    amountNeeded: 'Amount needed',
    addIngredient: 'Add Ingredient',
    noIngredientsAdded: 'No ingredients added',
    calculatedCost: 'Calculated Cost',
    perUnit: 'per unit',
    addIngredientsToCalculate: 'Add ingredients to calculate',

    // Validation messages
    nameRequired: 'Name is required',
    mustBeValidNumber: 'Must be a valid number',
    invalidEmailFormat: 'Invalid email format',
    categoryRequired: 'Category is required',
    validAmountRequired: 'Valid amount is required',
    dateRequired: 'Date is required',
    selectRecurringPeriod: 'Select recurring period',
    hireDateRequired: 'Hire date is required',
    pleaseSelectClient: 'Please select a client',
    addAtLeastOneProduct: 'Add at least one product',
    allItemsMustHaveDetails: 'All items must have product, quantity, and price',
    supplierName: 'Supplier Name',
    currentBalance: 'Current Balance (DZD)',
    youOweSupplier: 'Positive = you owe supplier, Negative = supplier owes you',
    fullName: 'Full Name',
    rolePosition: 'Role / Position',
    addEmployeeBtn: 'Add Employee',
    daily: 'Daily',
    selectPeriod: 'Select period',
    saleDetails: 'Sale Details',
    payment: 'Payment',
    amountPaidDZD: 'Amount Paid (DZD)',
    addProduct: 'Add Product',
    selectProductPlaceholder: 'Select product...',
    selectClientPlaceholder: 'Select client...',
    noProductsAdded: 'No products added yet',
    clickAddProduct: 'Click "Add Product" to add items to this sale',
    orderNotes: 'Order notes...',
    productDetails: 'Product Details',
    sellingPriceDZD: 'Selling Price (DZD)',
    manualCostOptional: 'Manual Cost (optional)',
    unitPieces: 'Pieces (pcs)',
    unitKilogram: 'Kilogram (kg)',
    unitBox: 'Box',
    unitPack: 'Pack',
    selectIngredientPlaceholder: 'Select ingredient...',
    noIngredientsYet: 'No ingredients added yet',
    clickAddIngredientHint: 'Click "Add Ingredient" to build the recipe',
    calculatedIngredientCost: 'Calculated Ingredient Cost',
    profitMargin: 'Profit Margin',
    autoCalculate: 'Auto-calculate',
    available: 'available',

    // Documents & Reports
    documents: 'Documents',
    documentsReports: 'Documents & Reports',
    generateDocuments: 'Generate invoices, delivery notes and business reports',
    documentPrefixes: 'Document Prefixes',
    invoicePrefix: 'Invoice Prefix',
    deliveryNotePrefix: 'Delivery Note Prefix',
    proformaPrefix: 'Proforma Prefix',
    salesDocsDesc: 'Invoices, Delivery Notes, Proformas',
    reportsDesc: 'Stock, Sales, Clients, Expenses Reports',
    invoices: 'Invoices',
    deliveryNotes: 'Delivery Notes',
    salesDocuments: 'Sales Documents',
    businessReports: 'Business Reports',
    invoice: 'Invoice',
    invoiceDesc: 'Official billing document for payment',
    deliveryNote: 'Delivery Note',
    deliveryNoteDesc: 'Proof of goods delivery',
    proformaInvoice: 'Proforma Invoice',
    proformaInvoiceDesc: 'Quote before sale confirmation',
    proformaDesc: 'Preliminary invoice before final billing',
    purchaseOrder: 'Purchase Order',
    purchaseOrderDesc: 'Client order before delivery',
    exitVoucher: 'Exit Voucher',
    exitVoucherDesc: 'Internal stock withdrawal record',
    creditNote: 'Credit Note',
    creditNoteDesc: 'Returns and refunds',
    quoteEstimate: 'Quote / Estimate',
    quoteEstimateDesc: 'Formal pricing for clients',
    receptionVoucher: 'Reception Voucher',
    receptionVoucherDesc: 'Goods received from supplier',
    monthlySummary: 'Monthly Summary',
    monthlySummaryDesc: 'Sales, expenses and profit overview',
    productSheet: 'Product Sheet',
    productSheetDesc: 'Product catalog with details',
    productionReport: 'Production Report',
    productionReportDesc: 'Production batch history and costs',
    selectDocumentType: 'Select Document Type',
    whatDocumentGenerate: 'Which document would you like to generate?',
    skipDocument: 'Skip',
    documentCenter: 'Document Center',
    conditionsGenerales: 'General Terms & Conditions',
    validUntil: 'Valid Until',
    deliveryDate: 'Expected Delivery Date',
    paymentConditions: 'Payment Conditions',
    originalInvoice: 'Original Invoice',
    returnReason: 'Return Reason',
    authorizedBy: 'Authorized By',
    warehouseLocation: 'Warehouse Location',
    receivedBy: 'Received By',
    qualityCheck: 'Quality Check',
    supplierInfo: 'Supplier Information',
    batchDetails: 'Batch Details',
    ingredientCost: 'Ingredient Cost',
    yieldQuantity: 'Yield Quantity',
    stockReport: 'Stock Report',
    stockReportDesc: 'Current inventory levels and values',
    salesReport: 'Sales Report',
    salesReportDesc: 'Sales summary by period',
    clientStatement: 'Client Statement',
    clientStatementDesc: 'Client debts and payment history',
    expenseReport: 'Expense Report',
    expenseReportDesc: 'Expense summary by category',
    recentDocuments: 'Recent Documents',
    noDocumentsYet: 'No documents generated yet',
    generateFirstDocument: 'Generate your first document from a sale',
    companySettings: 'Company Settings',
    companyInfo: 'Company Information',
    legalInfo: 'Legal Information',
    businessNameAr: 'Business Name (Arabic)',
    businessNameFr: 'Business Name (French)',
    businessAddress: 'Business Address',
    businessPhone: 'Business Phone',
    businessEmail: 'Business Email',
    nif: 'NIF (Tax ID)',
    rc: 'RC (Trade Register)',
    ai: 'AI (Article of Imposition)',
    nis: 'NIS (Statistical ID)',
    rib: 'RIB (Bank Account)',
    tvaRate: 'TVA Rate (%)',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings saved successfully',
    generateDocument: 'Generate Document',
    generateInvoice: 'Generate Invoice',
    generateDeliveryNote: 'Generate Delivery Note',
    generateProforma: 'Generate Proforma',
    printDocument: 'Print Document',
    printReport: 'Print Report',
    generateReport: 'Generate Report',
    reportSummary: 'Report Summary',
    back: 'Back',
    downloadPdf: 'Download PDF',
    documentNumber: 'Document Number',
    documentDate: 'Document Date',
    selectSale: 'Select a sale',
    selectDateRange: 'Select date range',
    fromDate: 'From Date',
    toDate: 'To Date',
    preview: 'Preview',
    print: 'Print',
    close: 'Close',

    // POS (Point of Sale)
    pos: 'Sales POS',
    pointOfSale: 'Quick sales with barcode scanning',
    scanBarcode: 'Scan barcode or enter code...',
    cart: 'Cart',
    cartEmpty: 'Cart is empty',
    scanOrSelectProducts: 'Scan barcode or select products',
    addedToCart: 'added to cart',
    productNotFound: 'Product not found',
    multipleProductsFound: 'Multiple products found',
    scanError: 'Scan error occurred',
    confirmClearCart: 'Clear all items from cart?',
    walkInCustomer: 'Walk-in Customer',
    noPhone: 'No phone',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    credit: 'Credit',
    exactAmount: 'Exact',
    change: 'Change',
    completeSale: 'Complete Sale',
    saleCompleted: 'Sale completed successfully!',
    saleError: 'Error completing sale',
    generateDocumentQuestion: 'Generate invoice for this sale?',
    favorites: 'Favorites',
    keyboardShortcuts: 'Keyboard Shortcuts',
    focusBarcodeScanner: 'Focus barcode scanner',
    focusProductSearch: 'Focus product search',
    toggleFavorites: 'Toggle favorites view',
    openPayment: 'Open payment',
    clearCart: 'Clear cart',
    closeModal: 'Close modal',
    errorLoadingData: 'Error loading data',
    pay: 'Pay',

    // Theme
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    appearance: 'Appearance',

    // Language
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    french: 'French',

    // Months
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',

    // Sales History
    salesHistory: 'Sales History',
    today: 'Today',
    thisWeek: 'This Week',
    customRange: 'Custom Range',
    startDate: 'Start Date',
    endDate: 'End Date',
    apply: 'Apply',
    transactions: 'Transactions',
    totalPaid: 'Total Paid',
    noSalesFound: 'No sales found',
    tryDifferentDateRange: 'Try selecting a different date range',
    filterByDate: 'Filter by Date',
    allTime: 'All Time',

    // Authentication
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    incorrectCredentials: 'Incorrect username or password',
    loginToAccount: 'Login to your account',
    enterCredentials: 'Enter your credentials to access the system',
    loggingIn: 'Logging in...',
    welcomeUser: 'Welcome',
    logoutConfirm: 'Are you sure you want to logout?',

    // User Management
    userManagement: 'User Management',
    addUser: 'Add User',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    users: 'Users',
    admin: 'Admin',
    manager: 'Manager',
    salesRole: 'Sales',
    userRole: 'Role',
    lastLogin: 'Last Login',
    neverLoggedIn: 'Never',
    userCreated: 'User created successfully',
    userUpdated: 'User updated successfully',
    userDeleted: 'User deleted successfully',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    cannotDeleteSelf: 'You cannot delete your own account',
    passwordMinLength: 'Password must be at least 6 characters',
    usernameRequired: 'Username is required',
    passwordRequired: 'Password is required',
    leaveBlankPassword: 'Leave blank to keep current password',

    // System Reset
    systemReset: 'System Reset',
    resetSystem: 'Reset System',
    resetWarning: 'Warning: This will permanently delete all data!',
    resetDescription: 'This action will clear all sales, stock, clients, suppliers, expenses, and other business data. Only user accounts and settings will be preserved.',
    confirmReset: 'Type your password to confirm reset',
    resetSuccess: 'System has been reset successfully',
    resetError: 'Error resetting system',
    dataCleared: 'All data has been cleared',
    irreversibleAction: 'This action cannot be undone!',

    // Resale Products
    resaleProducts: 'Resale Products',
    resaleProduct: 'Resale Product',
    addResaleProduct: 'Add Resale Product',
    editResaleProduct: 'Edit Resale Product',
    purchasePrice: 'Purchase Price',
    barcode: 'Barcode',
    sku: 'SKU',
    inStock: 'In Stock',
    reorderLevel: 'Reorder Level',
    resale: 'Resale',
    manufactured: 'Manufactured',
    productType: 'Product Type',
    searchResaleProducts: 'Search resale products...',
    noResaleProductsYet: 'No resale products yet',
    addFirstResaleProduct: 'Add your first resale product',

    // Settings Page
    generalSettings: 'General Settings',
    securitySettings: 'Security Settings',
    dangerZone: 'Danger Zone',
    businessSettings: 'Business Settings',
    systemSettings: 'System Settings',

    // Resale/Inventory additions
    resaleProductDesc: 'Buy and sell directly without production',
    purchasePriceDZD: 'Purchase Price (DZD)',
    resaleProductNote: 'Resale Product',
    resaleProductInfo: 'This product will be purchased and sold directly. Use "Add Stock" in the inventory page to add quantities.',
    profitPerUnit: 'Profit per unit',
    resaleStockPurchase: 'Resale stock purchase',
    currentStock: 'Current Stock',
    quantityToAdd: 'Quantity to Add',
    unitCostDZD: 'Unit Cost (DZD)',
    purchaseNotes: 'Purchase notes...',
    discount: 'Discount',

    // Payroll additions
    payrollDescription: 'This will create payroll records for all active employees for the selected month.',
    payrollSkipWarning: 'This will skip employees who already have payroll for this month.',
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    stock: 'المخزون',
    inventory: 'المنتجات',
    clients: 'العملاء',
    employers: 'الموظفين',
    expenses: 'المصاريف',
    reports: 'التقارير',
    suppliers: 'الموردين',
    settings: 'الإعدادات',
    mainMenu: 'القائمة الرئيسية',

    // Dashboard
    welcomeBack: 'مرحباً بعودتك! إليك ما يحدث في عملك.',
    monthRevenue: 'إيرادات الشهر',
    monthExpenses: 'مصاريف الشهر',
    netProfit: 'صافي الربح',
    stockValue: 'قيمة المخزون',
    production: 'الإنتاج',
    receivable: 'المستحقات',
    payable: 'الديون',
    pendingPayroll: 'الرواتب المعلقة',
    salesThisMonth: 'مبيعات هذا الشهر',
    expensesCount: 'مصروفات',
    thisMonth: 'هذا الشهر',
    itemsInStock: 'عناصر في المخزون',
    batchesThisMonth: 'دفعات هذا الشهر',
    fromClients: 'من العملاء',
    toSuppliers: 'للموردين',
    pending: 'معلق',
    alertsNotifications: 'التنبيهات والإشعارات',
    lowStockAlert: 'تنبيه نقص المخزون',
    itemsBelowMin: 'عناصر أقل من الحد الأدنى',
    viewDetails: 'عرض التفاصيل',
    pendingPayrollAlert: 'الرواتب المعلقة',
    salaryPaymentsPending: 'دفعات رواتب معلقة',
    processPayroll: 'معالجة الرواتب',
    outstandingPayments: 'المدفوعات المستحقة',
    pendingFromClients: 'مستحقة من العملاء',
    viewClients: 'عرض العملاء',
    allGood: 'كل شيء على ما يرام!',
    noAlerts: 'لا توجد تنبيهات حرجة. عملك يسير بسلاسة.',
    refresh: 'تحديث',

    // Stock
    stockManagement: 'إدارة المخزون',
    trackRawMaterials: 'إدارة المواد الخام والمكونات',
    addStock: 'إضافة مخزون',
    search: 'بحث',
    searchStock: 'البحث في المخزون...',
    allCategories: 'جميع الفئات',
    lowStockOnly: 'المخزون المنخفض فقط',
    totalItems: 'إجمالي العناصر',
    lowStock: 'مخزون منخفض',
    outOfStock: 'نفذ من المخزون',
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    totalValue: 'القيمة الإجمالية',
    noStockItems: 'لا توجد عناصر مخزون بعد',
    noMatchingItems: 'لا توجد عناصر مطابقة',
    addFirstStock: 'ابدأ بإضافة أول عنصر مخزون',
    tryAdjustingFilters: 'حاول تعديل الفلاتر',
    addStockItem: 'إضافة عنصر مخزون',
    item: 'العنصر',
    unitCost: 'تكلفة الوحدة',
    value: 'القيمة',
    ok: 'جيد',
    low: 'منخفض',
    deleteItem: 'حذف العنصر؟',
    cannotBeUndone: 'لا يمكن التراجع عن هذا الإجراء.',
    areYouSureDelete: 'هل أنت متأكد من حذف',
    removeStock: 'إزالة مخزون',
    current: 'الحالي',
    quantityTo: 'الكمية لـ',
    reasonForAdjustment: 'سبب التعديل',

    // Common
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    actions: 'الإجراءات',
    name: 'الاسم',
    description: 'الوصف',
    quantity: 'الكمية',
    unit: 'الوحدة',
    price: 'السعر',
    cost: 'التكلفة',
    total: 'المجموع',
    date: 'التاريخ',
    status: 'الحالة',
    notes: 'ملاحظات',
    phone: 'الهاتف',
    address: 'العنوان',
    email: 'البريد الإلكتروني',
    balance: 'الرصيد',
    category: 'الفئة',
    from: 'من',
    uncategorized: 'غير مصنف',
    remove: 'إزالة',
    items: 'عناصر',
    orders: 'طلبات',
    clear: 'مسح',

    // Products/Inventory
    products: 'المنتجات',
    createProduct: 'إنشاء منتج',
    productName: 'اسم المنتج',
    sellingPrice: 'سعر البيع',
    recipe: 'الوصفة',
    ingredients: 'المكونات',
    productionBatches: 'دفعات الإنتاج',
    startProduction: 'بدء الإنتاج',
    inventoryProduction: 'المنتجات / الإنتاج',
    createProductsAndManage: 'إنشاء المنتجات وإدارة دفعات الإنتاج',
    totalProducts: 'إجمالي المنتجات',
    unitsProduced: 'وحدات منتجة',
    productionCost: 'تكلفة الإنتاج',
    productionHistory: 'سجل الإنتاج',
    searchProducts: 'البحث في المنتجات...',
    searchProductionBatches: 'البحث في دفعات الإنتاج...',
    noProductsYet: 'لا توجد منتجات بعد',
    noProductsMatch: 'لا توجد منتجات مطابقة للبحث',
    createFirstProduct: 'أنشئ أول منتج لبدء الإنتاج',
    tryDifferentSearch: 'جرب بحثاً مختلفاً',
    totalProduced: 'إجمالي الإنتاج',
    noBatchesYet: 'لا يوجد سجل إنتاج بعد',
    noBatchesMatch: 'لا توجد دفعات مطابقة للبحث',
    startProducingToSee: 'ابدأ الإنتاج لرؤية السجل هنا',
    quantityToProduce: 'الكمية المراد إنتاجها',
    numberOfUnits: 'عدد',
    expenseAllocation: 'تخصيص المصاريف (د.ج)',
    expenseAllocationHint: 'مثل الكهرباء، تكاليف العمالة',
    productionDate: 'تاريخ الإنتاج',
    productionNotes: 'ملاحظات الإنتاج...',
    deleteProduct: 'حذف المنتج',
    deleteProductWarning: 'سيتم حذف جميع الوصفات والدفعات',

    // Clients
    clientManagement: 'إدارة العملاء',
    manageClients: 'إدارة قاعدة بيانات العملاء والمبيعات',
    addClient: 'إضافة عميل',
    searchClients: 'البحث في العملاء...',
    totalClients: 'إجمالي العملاء',
    allClientCategories: 'كل فئات العملاء',
    clientCategory: 'فئة العميل',
    noCategory: 'بدون فئة',
    selectClientCategory: 'اختر فئة العميل...',
    createNewCategory: 'إنشاء فئة جديدة',
    newCategoryName: 'اسم الفئة الجديدة',
    categoryNameRequired: 'اسم الفئة مطلوب',
    withDebt: 'مع ديون',
    totalSales: 'إجمالي المبيعات',
    totalRevenue: 'إجمالي الإيرادات',
    outstanding: 'المستحقات',
    noClientsYet: 'لا يوجد عملاء بعد',
    startAddingCustomers: 'ابدأ بإضافة عملائك إلى قاعدة البيانات',
    addFirstClient: 'إضافة أول عميل',
    viewSales: 'عرض المبيعات',
    showingSalesFor: 'عرض مبيعات:',
    allStatus: 'جميع الحالات',
    searchSales: 'البحث في المبيعات...',
    noSalesYet: 'لا توجد مبيعات بعد',
    startRecordingSales: 'ابدأ بتسجيل المبيعات لتتبع الإيرادات',
    createFirstSale: 'إنشاء أول بيع',
    addPayment: 'إضافة دفعة',
    client: 'العميل',
    alreadyPaid: 'المدفوع مسبقاً',
    remaining: 'المتبقي',
    paymentAmount: 'مبلغ الدفع (د.ج)',
    enterAmount: 'أدخل المبلغ...',
    recordPayment: 'تسجيل الدفعة',
    totalPurchases: 'إجمالي المشتريات',

    // Sales
    sales: 'المبيعات',
    newSale: 'بيع جديد',
    saleItems: 'عناصر البيع',
    paid: 'مدفوع',
    partial: 'جزئي',
    unpaid: 'غير مدفوع',

    // Expenses
    expenseManagement: 'إدارة المصاريف',
    trackExpenses: 'تتبع وإدارة جميع مصاريف العمل',
    addExpense: 'إضافة مصروف',
    totalExpenses: 'إجمالي المصاريف',
    averageExpense: 'متوسط المصروف',
    categories: 'الفئات',
    searchExpenses: 'البحث في المصاريف...',
    recurring: 'متكرر',
    noExpensesYet: 'لا توجد مصاريف مسجلة',
    noExpensesMatch: 'لا توجد مصاريف مطابقة للفلاتر',
    startTrackingExpenses: 'ابدأ بتتبع مصاريف عملك',
    tryAdjustingSearch: 'حاول تعديل البحث أو الفلاتر',
    recordExpense: 'تسجيل مصروف',
    deleteExpense: 'حذف المصروف',

    // Employers
    employerManagement: 'إدارة الموظفين',
    manageEmployees: 'إدارة فريقك والرواتب',
    addEmployer: 'إضافة موظف',
    salary: 'الراتب',
    role: 'الدور',
    payroll: 'كشف الرواتب',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفين النشطين',
    monthlySalaries: 'الرواتب الشهرية',
    pendingPayments: 'المدفوعات المعلقة',
    employees: 'الموظفين',
    searchEmployees: 'البحث في الموظفين...',
    searchPayroll: 'البحث في الرواتب...',
    activeOnly: 'النشطين فقط',
    noEmployeesYet: 'لا يوجد موظفين بعد',
    addTeamMembers: 'أضف أعضاء فريقك لإدارة الرواتب',
    addFirstEmployee: 'إضافة أول موظف',
    noPayrollRecords: 'لا توجد سجلات رواتب',
    generatePayrollForEmployees: 'إنشاء رواتب للموظفين',
    generatePayroll: 'إنشاء الرواتب',
    period: 'الفترة',
    employee: 'الموظف',
    amount: 'المبلغ',
    markAsPaid: 'تحديد كمدفوع',
    generate: 'إنشاء',
    generatePayrollDescription: 'سيتم إنشاء سجلات رواتب لجميع الموظفين النشطين للشهر المحدد.',
    year: 'السنة',
    month: 'الشهر',
    skipExistingPayroll: 'سيتم تخطي الموظفين الذين لديهم رواتب لهذا الشهر.',
    hired: 'تاريخ التوظيف',
    monthlySalary: 'الراتب الشهري',
    noRoleAssigned: 'بدون دور',
    active: 'نشط',
    inactive: 'غير نشط',

    // Suppliers
    supplierManagement: 'إدارة الموردين',
    manageSuppliers: 'إدارة شبكة الموردين والمشتريات',
    addSupplier: 'إضافة مورد',
    totalSuppliers: 'إجمالي الموردين',
    totalPurchasesAmount: 'إجمالي المشتريات',
    outstandingDebt: 'الديون المستحقة',
    searchSuppliers: 'البحث في الموردين...',
    noSuppliersYet: 'لا يوجد موردين بعد',
    noSuppliersMatch: 'لا يوجد موردين مطابقين للفلاتر',
    addSuppliersToManage: 'أضف الموردين لإدارة الطلبات والمخزون',
    addFirstSupplier: 'إضافة أول مورد',
    deleteSupplier: 'حذف المورد',
    deleteSupplierWarning: 'سيتم أيضاً حذف جميع المشتريات',
    purchases: 'مشتريات',

    // Reports
    reportsAnalytics: 'التقارير والتحليلات',
    viewReports: 'تحليلات الأعمال ورؤى الأداء',
    profitLoss: 'الأرباح والخسائر',
    stockAlerts: 'تنبيهات المخزون',
    monthProfit: 'ربح الشهر',
    receivableClients: 'المستحقات (العملاء)',
    payableSuppliers: 'الديون (الموردين)',
    lowStockItems: 'عناصر المخزون المنخفض',
    monthProduction: 'إنتاج الشهر',
    batches: 'دفعات',
    collectedThisMonth: 'المحصل هذا الشهر',
    to: 'إلى',
    revenue: 'الإيرادات',
    productionCosts: 'تكاليف الإنتاج',
    margin: 'هامش',
    monthlyProfitLoss: 'الأرباح/الخسائر الشهرية',
    profit: 'الربح',
    stockByCategory: 'المخزون حسب الفئة',
    noLowStockItems: 'لا توجد عناصر منخفضة المخزون',
    minimum: 'الحد الأدنى',
    shortage: 'النقص',
    supplier: 'المورد',
    topProducts: 'أفضل المنتجات',
    noSalesData: 'لا توجد بيانات مبيعات',
    unitsSold: 'وحدات مباعة',
    salesByClient: 'المبيعات حسب العميل',
    noClientData: 'لا توجد بيانات عملاء',
    owes: 'مدين بـ',
    monthlySales: 'المبيعات الشهرية',
    collected: 'المحصل',
    expensesByCategory: 'المصاريف حسب الفئة',
    monthlyExpenses: 'المصاريف الشهرية',
    count: 'العدد',
    productionByProduct: 'الإنتاج حسب المنتج',
    noProductionData: 'لا توجد بيانات إنتاج',
    avgUnitCost: 'متوسط تكلفة الوحدة',
    recentProductionHistory: 'سجل الإنتاج الأخير',
    noProductionHistory: 'لا يوجد سجل إنتاج',
    totalAmount: 'المبلغ الإجمالي',
    totalCost: 'التكلفة الإجمالية',
    product: 'المنتج',
    businessAnalytics: 'تحليلات الأعمال ورؤى الأداء',

    // Confirm dialogs
    confirmDeleteClient: 'هل أنت متأكد؟ سيتم أيضاً حذف جميع المبيعات لهذا العميل.',
    confirmDeleteSale: 'هل أنت متأكد من حذف هذا البيع؟',
    confirmDeleteEmployee: 'هل أنت متأكد؟ سيتم أيضاً حذف جميع سجلات الرواتب لهذا الموظف.',
    confirmDeletePayroll: 'هل أنت متأكد من حذف سجل الراتب هذا؟',
    willDeletePurchases: 'سيتم أيضاً حذف جميع المشتريات',

    // Modal titles
    editStockItem: 'تعديل عنصر المخزون',
    editClient: 'تعديل العميل',
    addNewClient: 'إضافة عميل جديد',
    editSupplier: 'تعديل المورد',
    editEmployee: 'تعديل الموظف',
    addNewEmployee: 'إضافة موظف جديد',
    editExpense: 'تعديل المصروف',
    editSale: 'تعديل البيع',
    editProduct: 'تعديل المنتج',
    createProductTitle: 'إنشاء منتج',

    // Form labels
    itemName: 'اسم العنصر',
    selectCategory: 'اختر الفئة',
    selectSupplier: 'اختر المورد (اختياري)',
    currentQuantity: 'الكمية الحالية',
    initialQuantity: 'الكمية الأولية',
    costPerUnit: 'تكلفة الوحدة (د.ج)',
    lowStockAlertThreshold: 'حد تنبيه المخزون المنخفض',
    alertWhenBelow: 'تنبيه عندما تنخفض الكمية عن هذا',
    useStockAdjustments: 'استخدم تعديلات المخزون لتغيير الكمية',
    additionalNotes: 'ملاحظات إضافية...',
    update: 'تحديث',
    clientName: 'اسم العميل',
    optional: 'اختياري',
    initialBalance: 'الرصيد الأولي (د.ج)',
    amountOwed: 'المبلغ المستحق من العميل',
    selectClient: 'اختر عميل',
    saleDate: 'تاريخ البيع',
    selectProduct: 'اختر المنتج',
    qty: 'الكمية',
    addItem: 'إضافة عنصر',
    summary: 'الملخص',
    subtotal: 'المجموع الفرعي',
    paidAmount: 'المبلغ المدفوع',
    amountPaidNow: 'المبلغ المدفوع الآن',
    createSale: 'إنشاء بيع',
    hireDate: 'تاريخ التوظيف',
    monthlySalaryAmount: 'الراتب الشهري (د.ج)',
    employeeIsActive: 'الموظف نشط',
    expenseCategory: 'فئة المصروف',
    expenseAmount: 'المبلغ (د.ج)',
    expenseDate: 'التاريخ',
    isRecurring: 'هذا مصروف متكرر',
    recurringPeriod: 'فترة التكرار',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    yearly: 'سنوي',
    manualCostPerUnit: 'التكلفة اليدوية للوحدة (د.ج)',
    overrideRecipeCost: 'تجاوز حساب تكلفة الوصفة',
    recipeIngredients: 'الوصفة / المكونات',
    ingredientsList: 'حدد المكونات المطلوبة لكل وحدة',
    selectIngredient: 'اختر المكون',
    amountNeeded: 'الكمية المطلوبة',
    addIngredient: 'إضافة مكون',
    noIngredientsAdded: 'لم تتم إضافة مكونات',
    calculatedCost: 'التكلفة المحسوبة',
    perUnit: 'للوحدة',
    addIngredientsToCalculate: 'أضف المكونات للحساب',

    // Validation messages
    nameRequired: 'الاسم مطلوب',
    mustBeValidNumber: 'يجب أن يكون رقماً صحيحاً',
    invalidEmailFormat: 'صيغة البريد الإلكتروني غير صحيحة',
    categoryRequired: 'الفئة مطلوبة',
    validAmountRequired: 'مبلغ صحيح مطلوب',
    dateRequired: 'التاريخ مطلوب',
    selectRecurringPeriod: 'اختر فترة التكرار',
    hireDateRequired: 'تاريخ التوظيف مطلوب',
    pleaseSelectClient: 'الرجاء اختيار عميل',
    addAtLeastOneProduct: 'أضف منتج واحد على الأقل',
    allItemsMustHaveDetails: 'يجب أن تحتوي جميع العناصر على المنتج والكمية والسعر',
    supplierName: 'اسم المورد',
    currentBalance: 'الرصيد الحالي (د.ج)',
    youOweSupplier: 'موجب = أنت مدين للمورد، سالب = المورد مدين لك',
    fullName: 'الاسم الكامل',
    rolePosition: 'الدور / المنصب',
    addEmployeeBtn: 'إضافة موظف',
    daily: 'يومي',
    selectPeriod: 'اختر الفترة',
    saleDetails: 'تفاصيل البيع',
    payment: 'الدفع',
    amountPaidDZD: 'المبلغ المدفوع (د.ج)',
    addProduct: 'إضافة منتج',
    selectProductPlaceholder: 'اختر المنتج...',
    selectClientPlaceholder: 'اختر العميل...',
    noProductsAdded: 'لم تتم إضافة منتجات بعد',
    clickAddProduct: 'انقر على "إضافة منتج" لإضافة عناصر لهذا البيع',
    orderNotes: 'ملاحظات الطلب...',
    productDetails: 'تفاصيل المنتج',
    sellingPriceDZD: 'سعر البيع (د.ج)',
    manualCostOptional: 'التكلفة اليدوية (اختياري)',
    unitPieces: 'قطع',
    unitKilogram: 'كيلوغرام (كغ)',
    unitBox: 'صندوق',
    unitPack: 'عبوة',
    selectIngredientPlaceholder: 'اختر المكون...',
    noIngredientsYet: 'لم تتم إضافة مكونات بعد',
    clickAddIngredientHint: 'انقر على "إضافة مكون" لبناء الوصفة',
    calculatedIngredientCost: 'تكلفة المكونات المحسوبة',
    profitMargin: 'هامش الربح',
    autoCalculate: 'حساب تلقائي',
    available: 'متوفر',

    // POS (Point of Sale)
    pos: 'نقطة البيع',
    pointOfSale: 'بيع سريع مع مسح الباركود',
    scanBarcode: 'امسح الباركود أو أدخل الرمز...',
    cart: 'السلة',
    cartEmpty: 'السلة فارغة',
    scanOrSelectProducts: 'امسح الباركود أو اختر المنتجات',
    addedToCart: 'تمت الإضافة للسلة',
    productNotFound: 'المنتج غير موجود',
    multipleProductsFound: 'تم العثور على منتجات متعددة',
    scanError: 'حدث خطأ في المسح',
    confirmClearCart: 'مسح جميع العناصر من السلة؟',
    walkInCustomer: 'زبون عابر',
    noPhone: 'بدون هاتف',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقداً',
    credit: 'آجل',
    exactAmount: 'المبلغ بالضبط',
    change: 'الباقي',
    completeSale: 'إتمام البيع',
    saleCompleted: 'تم البيع بنجاح!',
    saleError: 'خطأ في إتمام البيع',
    generateDocumentQuestion: 'إنشاء فاتورة لهذا البيع؟',
    favorites: 'المفضلة',
    keyboardShortcuts: 'اختصارات لوحة المفاتيح',
    focusBarcodeScanner: 'التركيز على ماسح الباركود',
    focusProductSearch: 'التركيز على بحث المنتج',
    toggleFavorites: 'تبديل عرض المفضلة',
    openPayment: 'فتح الدفع',
    clearCart: 'مسح السلة',
    closeModal: 'إغلاق النافذة',
    errorLoadingData: 'خطأ في تحميل البيانات',
    pay: 'دفع',

    // Theme
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    appearance: 'المظهر',

    // Language
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    french: 'الفرنسية',

    // Months
    january: 'يناير',
    february: 'فبراير',
    march: 'مارس',
    april: 'أبريل',
    may: 'مايو',
    june: 'يونيو',
    july: 'يوليو',
    august: 'أغسطس',
    september: 'سبتمبر',
    october: 'أكتوبر',
    november: 'نوفمبر',
    december: 'ديسمبر',

    // Documents & Reports
    documents: 'الوثائق',
    documentsReports: 'الوثائق والتقارير',
    generateDocuments: 'إنشاء الفواتير وسندات التسليم وتقارير الأعمال',
    documentPrefixes: 'بادئات الوثائق',
    invoicePrefix: 'بادئة الفاتورة',
    deliveryNotePrefix: 'بادئة سند التسليم',
    proformaPrefix: 'بادئة الفاتورة المبدئية',
    salesDocsDesc: 'الفواتير، سندات التسليم، الفواتير المبدئية',
    reportsDesc: 'تقارير المخزون، المبيعات، العملاء، المصاريف',
    invoices: 'الفواتير',
    deliveryNotes: 'سندات التسليم',
    salesDocuments: 'وثائق المبيعات',
    businessReports: 'تقارير الأعمال',
    invoice: 'فاتورة',
    invoiceDesc: 'وثيقة الفوترة الرسمية للدفع',
    deliveryNote: 'سند التسليم',
    deliveryNoteDesc: 'إثبات تسليم البضائع',
    proformaInvoice: 'فاتورة مبدئية',
    proformaInvoiceDesc: 'عرض سعر قبل تأكيد البيع',
    proformaDesc: 'فاتورة أولية قبل الفوترة النهائية',
    purchaseOrder: 'طلب شراء',
    purchaseOrderDesc: 'طلب العميل قبل التسليم',
    exitVoucher: 'سند الخروج',
    exitVoucherDesc: 'سجل سحب المخزون الداخلي',
    creditNote: 'إشعار دائن',
    creditNoteDesc: 'المرتجعات والمبالغ المستردة',
    quoteEstimate: 'عرض أسعار',
    quoteEstimateDesc: 'تسعير رسمي للعملاء',
    receptionVoucher: 'سند الاستلام',
    receptionVoucherDesc: 'البضائع المستلمة من المورد',
    monthlySummary: 'الملخص الشهري',
    monthlySummaryDesc: 'نظرة عامة على المبيعات والمصاريف والأرباح',
    productSheet: 'بطاقة المنتج',
    productSheetDesc: 'كتالوج المنتجات مع التفاصيل',
    productionReport: 'تقرير الإنتاج',
    productionReportDesc: 'سجل دفعات الإنتاج والتكاليف',
    selectDocumentType: 'اختر نوع الوثيقة',
    whatDocumentGenerate: 'أي وثيقة تريد إنشاءها؟',
    skipDocument: 'تخطي',
    documentCenter: 'مركز الوثائق',
    conditionsGenerales: 'الشروط والأحكام العامة',
    validUntil: 'صالح حتى',
    deliveryDate: 'تاريخ التسليم المتوقع',
    paymentConditions: 'شروط الدفع',
    originalInvoice: 'الفاتورة الأصلية',
    returnReason: 'سبب الإرجاع',
    authorizedBy: 'بتصريح من',
    warehouseLocation: 'موقع المستودع',
    receivedBy: 'استلمها',
    qualityCheck: 'فحص الجودة',
    supplierInfo: 'معلومات المورد',
    batchDetails: 'تفاصيل الدفعة',
    ingredientCost: 'تكلفة المكونات',
    yieldQuantity: 'كمية الإنتاج',
    stockReport: 'تقرير المخزون',
    stockReportDesc: 'مستويات وقيم المخزون الحالية',
    salesReport: 'تقرير المبيعات',
    salesReportDesc: 'ملخص المبيعات حسب الفترة',
    clientStatement: 'كشف حساب العميل',
    clientStatementDesc: 'ديون العميل وسجل المدفوعات',
    expenseReport: 'تقرير المصاريف',
    expenseReportDesc: 'ملخص المصاريف حسب الفئة',
    recentDocuments: 'الوثائق الأخيرة',
    noDocumentsYet: 'لم يتم إنشاء وثائق بعد',
    generateFirstDocument: 'أنشئ أول وثيقة من عملية بيع',
    companySettings: 'إعدادات الشركة',
    companyInfo: 'معلومات الشركة',
    legalInfo: 'المعلومات القانونية',
    businessNameAr: 'اسم الشركة (بالعربية)',
    businessNameFr: 'اسم الشركة (بالفرنسية)',
    businessAddress: 'عنوان الشركة',
    businessPhone: 'هاتف الشركة',
    businessEmail: 'بريد الشركة الإلكتروني',
    nif: 'رقم التعريف الجبائي (NIF)',
    rc: 'السجل التجاري (RC)',
    ai: 'المادة الضريبية (AI)',
    nis: 'رقم التعريف الإحصائي (NIS)',
    rib: 'رقم الحساب البنكي (RIB)',
    tvaRate: 'نسبة الرسم على القيمة المضافة (%)',
    saveSettings: 'حفظ الإعدادات',
    settingsSaved: 'تم حفظ الإعدادات بنجاح',
    generateDocument: 'إنشاء وثيقة',
    generateInvoice: 'إنشاء فاتورة',
    generateDeliveryNote: 'إنشاء سند تسليم',
    generateProforma: 'إنشاء فاتورة مبدئية',
    printDocument: 'طباعة الوثيقة',
    printReport: 'طباعة التقرير',
    generateReport: 'إنشاء تقرير',
    reportSummary: 'ملخص التقرير',
    back: 'رجوع',
    downloadPdf: 'تحميل PDF',
    documentNumber: 'رقم الوثيقة',
    documentDate: 'تاريخ الوثيقة',
    selectSale: 'اختر عملية بيع',
    selectDateRange: 'اختر نطاق التاريخ',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    preview: 'معاينة',
    print: 'طباعة',
    close: 'إغلاق',

    // Sales History
    salesHistory: 'سجل المبيعات',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    customRange: 'نطاق مخصص',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    apply: 'تطبيق',
    transactions: 'المعاملات',
    totalPaid: 'إجمالي المدفوع',
    noSalesFound: 'لا توجد مبيعات',
    tryDifferentDateRange: 'حاول اختيار نطاق تاريخ مختلف',
    filterByDate: 'فلترة حسب التاريخ',
    allTime: 'كل الوقت',

    // Authentication
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    incorrectCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    loginToAccount: 'تسجيل الدخول إلى حسابك',
    enterCredentials: 'أدخل بيانات الاعتماد للوصول إلى النظام',
    loggingIn: 'جاري تسجيل الدخول...',
    welcomeUser: 'مرحباً',
    logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',

    // User Management
    userManagement: 'إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل المستخدم',
    deleteUser: 'حذف المستخدم',
    users: 'المستخدمين',
    admin: 'مدير',
    manager: 'مشرف',
    salesRole: 'مبيعات',
    userRole: 'الدور',
    lastLogin: 'آخر دخول',
    neverLoggedIn: 'لم يسجل دخول',
    userCreated: 'تم إنشاء المستخدم بنجاح',
    userUpdated: 'تم تحديث المستخدم بنجاح',
    userDeleted: 'تم حذف المستخدم بنجاح',
    confirmDeleteUser: 'هل أنت متأكد من حذف هذا المستخدم؟',
    cannotDeleteSelf: 'لا يمكنك حذف حسابك الخاص',
    passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    usernameRequired: 'اسم المستخدم مطلوب',
    passwordRequired: 'كلمة المرور مطلوبة',
    leaveBlankPassword: 'اتركه فارغاً للإبقاء على كلمة المرور الحالية',

    // System Reset
    systemReset: 'إعادة تعيين النظام',
    resetSystem: 'إعادة تعيين النظام',
    resetWarning: 'تحذير: سيتم حذف جميع البيانات نهائياً!',
    resetDescription: 'هذا الإجراء سيمسح جميع المبيعات والمخزون والعملاء والموردين والمصاريف وبيانات العمل الأخرى. سيتم الاحتفاظ فقط بحسابات المستخدمين والإعدادات.',
    confirmReset: 'اكتب كلمة المرور لتأكيد إعادة التعيين',
    resetSuccess: 'تمت إعادة تعيين النظام بنجاح',
    resetError: 'خطأ في إعادة تعيين النظام',
    dataCleared: 'تم مسح جميع البيانات',
    irreversibleAction: 'لا يمكن التراجع عن هذا الإجراء!',

    // Resale Products
    resaleProducts: 'منتجات إعادة البيع',
    resaleProduct: 'منتج إعادة البيع',
    addResaleProduct: 'إضافة منتج إعادة بيع',
    editResaleProduct: 'تعديل منتج إعادة البيع',
    purchasePrice: 'سعر الشراء',
    barcode: 'الباركود',
    sku: 'رمز المنتج',
    inStock: 'في المخزون',
    reorderLevel: 'حد إعادة الطلب',
    resale: 'إعادة بيع',
    manufactured: 'مصنّع',
    productType: 'نوع المنتج',
    searchResaleProducts: 'البحث في منتجات إعادة البيع...',
    noResaleProductsYet: 'لا توجد منتجات إعادة بيع بعد',
    addFirstResaleProduct: 'أضف أول منتج إعادة بيع',

    // Settings Page
    generalSettings: 'الإعدادات العامة',
    securitySettings: 'إعدادات الأمان',
    dangerZone: 'منطقة الخطر',
    businessSettings: 'إعدادات العمل',
    systemSettings: 'إعدادات النظام',

    // Resale/Inventory additions
    resaleProductDesc: 'شراء وبيع مباشر بدون إنتاج',
    purchasePriceDZD: 'سعر الشراء (د.ج)',
    resaleProductNote: 'منتج إعادة بيع',
    resaleProductInfo: 'سيتم شراء وبيع هذا المنتج مباشرة. استخدم "إضافة مخزون" في صفحة المنتجات لإضافة الكميات.',
    profitPerUnit: 'الربح لكل وحدة',
    resaleStockPurchase: 'شراء مخزون إعادة بيع',
    currentStock: 'المخزون الحالي',
    quantityToAdd: 'الكمية المراد إضافتها',
    unitCostDZD: 'تكلفة الوحدة (د.ج)',
    purchaseNotes: 'ملاحظات الشراء...',
    discount: 'خصم',

    // Payroll additions
    payrollDescription: 'سيتم إنشاء سجلات رواتب لجميع الموظفين النشطين للشهر المحدد.',
    payrollSkipWarning: 'سيتم تخطي الموظفين الذين لديهم رواتب لهذا الشهر.',
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    stock: 'Stock',
    inventory: 'Inventaire',
    clients: 'Clients',
    employers: 'Employés',
    expenses: 'Dépenses',
    reports: 'Rapports',
    suppliers: 'Fournisseurs',
    settings: 'Paramètres',
    mainMenu: 'Menu Principal',

    // Dashboard
    welcomeBack: "Bon retour ! Voici l'état de votre activité.",
    monthRevenue: 'Revenus du mois',
    monthExpenses: 'Dépenses du mois',
    netProfit: 'Bénéfice net',
    stockValue: 'Valeur du stock',
    production: 'Production',
    receivable: 'Créances',
    payable: 'Dettes',
    pendingPayroll: 'Salaires en attente',
    salesThisMonth: 'ventes ce mois',
    expensesCount: 'dépenses',
    thisMonth: 'Ce mois',
    itemsInStock: 'articles en stock',
    batchesThisMonth: 'lots ce mois',
    fromClients: 'Des clients',
    toSuppliers: 'Aux fournisseurs',
    pending: 'En attente',
    alertsNotifications: 'Alertes et notifications',
    lowStockAlert: 'Alerte stock bas',
    itemsBelowMin: 'articles en dessous du minimum',
    viewDetails: 'Voir détails',
    pendingPayrollAlert: 'Salaires en attente',
    salaryPaymentsPending: 'paiements de salaires en attente',
    processPayroll: 'Traiter les salaires',
    outstandingPayments: 'Paiements en suspens',
    pendingFromClients: 'en attente des clients',
    viewClients: 'Voir clients',
    allGood: 'Tout va bien !',
    noAlerts: 'Aucune alerte critique. Votre activité fonctionne bien.',
    refresh: 'Actualiser',

    // Stock
    stockManagement: 'Gestion du stock',
    trackRawMaterials: 'Gérer vos matières premières et ingrédients',
    addStock: 'Ajouter stock',
    search: 'Rechercher',
    searchStock: 'Rechercher dans le stock...',
    allCategories: 'Toutes les catégories',
    lowStockOnly: 'Stock bas uniquement',
    totalItems: 'Total articles',
    lowStock: 'Stock bas',
    outOfStock: 'Rupture de stock',
    lowStockAlerts: 'Alertes stock bas',
    totalValue: 'Valeur totale',
    noStockItems: 'Aucun article en stock',
    noMatchingItems: 'Aucun article correspondant',
    addFirstStock: 'Commencez par ajouter votre premier article',
    tryAdjustingFilters: 'Essayez de modifier les filtres',
    addStockItem: 'Ajouter un article',
    item: 'Article',
    unitCost: 'Coût unitaire',
    value: 'Valeur',
    ok: 'OK',
    low: 'Bas',
    deleteItem: "Supprimer l'article ?",
    cannotBeUndone: 'Cette action est irréversible.',
    areYouSureDelete: 'Êtes-vous sûr de vouloir supprimer',
    removeStock: 'Retirer du stock',
    current: 'Actuel',
    quantityTo: 'Quantité à',
    reasonForAdjustment: "Raison de l'ajustement",

    // Common
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    yes: 'Oui',
    no: 'Non',
    actions: 'Actions',
    name: 'Nom',
    description: 'Description',
    quantity: 'Quantité',
    unit: 'Unité',
    price: 'Prix',
    cost: 'Coût',
    total: 'Total',
    date: 'Date',
    status: 'Statut',
    notes: 'Notes',
    phone: 'Téléphone',
    address: 'Adresse',
    email: 'E-mail',
    balance: 'Solde',
    category: 'Catégorie',
    from: 'De',
    uncategorized: 'Non classé',
    remove: 'Retirer',
    items: 'articles',
    orders: 'commandes',
    clear: 'Effacer',

    // Products/Inventory
    products: 'Produits',
    createProduct: 'Créer un produit',
    productName: 'Nom du produit',
    sellingPrice: 'Prix de vente',
    recipe: 'Recette',
    ingredients: 'Ingrédients',
    productionBatches: 'Lots de production',
    startProduction: 'Lancer la production',
    inventoryProduction: 'Inventaire / Production',
    createProductsAndManage: 'Créer des produits et gérer les lots de production',
    totalProducts: 'Total produits',
    unitsProduced: 'unités produites',
    productionCost: 'Coût de production',
    productionHistory: 'Historique de production',
    searchProducts: 'Rechercher des produits...',
    searchProductionBatches: 'Rechercher des lots...',
    noProductsYet: 'Aucun produit',
    noProductsMatch: 'Aucun produit correspondant',
    createFirstProduct: 'Créez votre premier produit pour démarrer la production',
    tryDifferentSearch: 'Essayez une recherche différente',
    totalProduced: 'Total produit',
    noBatchesYet: 'Aucun historique de production',
    noBatchesMatch: 'Aucun lot correspondant',
    startProducingToSee: 'Commencez à produire pour voir l\'historique',
    quantityToProduce: 'Quantité à produire',
    numberOfUnits: 'Nombre de',
    expenseAllocation: 'Allocation des dépenses (DZD)',
    expenseAllocationHint: 'ex: électricité, main d\'œuvre',
    productionDate: 'Date de production',
    productionNotes: 'Notes de production...',
    deleteProduct: 'Supprimer le produit',
    deleteProductWarning: 'Cela supprimera toutes les recettes et les lots',

    // Clients
    clientManagement: 'Gestion des clients',
    manageClients: 'Gérer votre base de données clients et ventes',
    addClient: 'Ajouter un client',
    searchClients: 'Rechercher des clients...',
    totalClients: 'Total clients',
    allClientCategories: 'Toutes les catégories client',
    clientCategory: 'Catégorie client',
    noCategory: 'Sans catégorie',
    selectClientCategory: 'Sélectionner une catégorie client...',
    createNewCategory: 'Créer une catégorie',
    newCategoryName: 'Nom de la nouvelle catégorie',
    categoryNameRequired: 'Le nom de la catégorie est requis',
    withDebt: 'Avec dette',
    totalSales: 'Total ventes',
    totalRevenue: 'Chiffre d\'affaires total',
    outstanding: 'Impayés',
    noClientsYet: 'Aucun client',
    startAddingCustomers: 'Commencez à ajouter vos clients',
    addFirstClient: 'Ajouter le premier client',
    viewSales: 'Voir les ventes',
    showingSalesFor: 'Ventes pour :',
    allStatus: 'Tous les statuts',
    searchSales: 'Rechercher des ventes...',
    noSalesYet: 'Aucune vente',
    startRecordingSales: 'Commencez à enregistrer les ventes',
    createFirstSale: 'Créer la première vente',
    addPayment: 'Ajouter un paiement',
    client: 'Client',
    alreadyPaid: 'Déjà payé',
    remaining: 'Restant',
    paymentAmount: 'Montant du paiement (DZD)',
    enterAmount: 'Saisir le montant...',
    recordPayment: 'Enregistrer le paiement',
    totalPurchases: 'Total achats',

    // Sales
    sales: 'Ventes',
    newSale: 'Nouvelle vente',
    saleItems: 'Articles de vente',
    paid: 'Payé',
    partial: 'Partiel',
    unpaid: 'Impayé',

    // Expenses
    expenseManagement: 'Gestion des dépenses',
    trackExpenses: 'Suivre et gérer toutes les dépenses',
    addExpense: 'Ajouter une dépense',
    totalExpenses: 'Total dépenses',
    averageExpense: 'Dépense moyenne',
    categories: 'Catégories',
    searchExpenses: 'Rechercher des dépenses...',
    recurring: 'Récurrent',
    noExpensesYet: 'Aucune dépense enregistrée',
    noExpensesMatch: 'Aucune dépense correspondante',
    startTrackingExpenses: 'Commencez à suivre vos dépenses',
    tryAdjustingSearch: 'Essayez de modifier votre recherche',
    recordExpense: 'Enregistrer la dépense',
    deleteExpense: 'Supprimer la dépense',

    // Employers
    employerManagement: 'Gestion des employés',
    manageEmployees: 'Gérer votre équipe et la paie',
    addEmployer: 'Ajouter un employé',
    salary: 'Salaire',
    role: 'Rôle',
    payroll: 'Paie',
    totalEmployees: 'Total employés',
    activeEmployees: 'Employés actifs',
    monthlySalaries: 'Salaires mensuels',
    pendingPayments: 'Paiements en attente',
    employees: 'Employés',
    searchEmployees: 'Rechercher des employés...',
    searchPayroll: 'Rechercher dans la paie...',
    activeOnly: 'Actifs uniquement',
    noEmployeesYet: 'Aucun employé',
    addTeamMembers: 'Ajoutez les membres de votre équipe',
    addFirstEmployee: 'Ajouter le premier employé',
    noPayrollRecords: 'Aucun enregistrement de paie',
    generatePayrollForEmployees: 'Générer la paie pour vos employés',
    generatePayroll: 'Générer la paie',
    period: 'Période',
    employee: 'Employé',
    amount: 'Montant',
    markAsPaid: 'Marquer comme payé',
    generate: 'Générer',
    generatePayrollDescription: 'Cela créera des fiches de paie pour tous les employés actifs du mois sélectionné.',
    year: 'Année',
    month: 'Mois',
    skipExistingPayroll: 'Les employés ayant déjà une fiche de paie pour ce mois seront ignorés.',
    hired: 'Embauché',
    monthlySalary: 'Salaire mensuel',
    noRoleAssigned: 'Aucun rôle',
    active: 'actif',
    inactive: 'inactif',

    // Suppliers
    supplierManagement: 'Gestion des fournisseurs',
    manageSuppliers: 'Gérer votre réseau de fournisseurs et achats',
    addSupplier: 'Ajouter un fournisseur',
    totalSuppliers: 'Total fournisseurs',
    totalPurchasesAmount: 'Total achats',
    outstandingDebt: 'Dettes en cours',
    searchSuppliers: 'Rechercher des fournisseurs...',
    noSuppliersYet: 'Aucun fournisseur',
    noSuppliersMatch: 'Aucun fournisseur correspondant',
    addSuppliersToManage: 'Ajoutez vos fournisseurs pour gérer les commandes',
    addFirstSupplier: 'Ajouter le premier fournisseur',
    deleteSupplier: 'Supprimer le fournisseur',
    deleteSupplierWarning: 'Cela supprimera aussi tous les achats',
    purchases: 'achats',

    // Reports
    reportsAnalytics: 'Rapports et analyses',
    viewReports: 'Analyses et indicateurs de performance',
    profitLoss: 'Profits et pertes',
    stockAlerts: 'Alertes stock',
    monthProfit: 'Profit du mois',
    receivableClients: 'Créances (Clients)',
    payableSuppliers: 'Dettes (Fournisseurs)',
    lowStockItems: 'Articles en stock bas',
    monthProduction: 'Production du mois',
    batches: 'lots',
    collectedThisMonth: 'Encaissé ce mois',
    to: 'à',
    revenue: 'Revenus',
    productionCosts: 'Coûts de production',
    margin: 'marge',
    monthlyProfitLoss: 'Profits/Pertes mensuels',
    profit: 'Profit',
    stockByCategory: 'Stock par catégorie',
    noLowStockItems: 'Aucun article en stock bas',
    minimum: 'Minimum',
    shortage: 'Manque',
    supplier: 'Fournisseur',
    topProducts: 'Meilleurs produits',
    noSalesData: 'Aucune donnée de vente',
    unitsSold: 'unités vendues',
    salesByClient: 'Ventes par client',
    noClientData: 'Aucune donnée client',
    owes: 'Doit',
    monthlySales: 'Ventes mensuelles',
    collected: 'Encaissé',
    expensesByCategory: 'Dépenses par catégorie',
    monthlyExpenses: 'Dépenses mensuelles',
    count: 'Nombre',
    productionByProduct: 'Production par produit',
    noProductionData: 'Aucune donnée de production',
    avgUnitCost: 'Coût unitaire moyen',
    recentProductionHistory: 'Historique de production récent',
    noProductionHistory: 'Aucun historique de production',
    totalAmount: 'Montant total',
    totalCost: 'Coût total',
    product: 'Produit',
    businessAnalytics: 'Analyses et indicateurs de performance',

    // Confirm dialogs
    confirmDeleteClient: 'Êtes-vous sûr ? Cela supprimera aussi toutes les ventes de ce client.',
    confirmDeleteSale: 'Êtes-vous sûr de vouloir supprimer cette vente ?',
    confirmDeleteEmployee: 'Êtes-vous sûr ? Cela supprimera aussi tous les enregistrements de paie.',
    confirmDeletePayroll: 'Êtes-vous sûr de vouloir supprimer cet enregistrement de paie ?',
    willDeletePurchases: 'Cela supprimera aussi tous les achats',

    // Modal titles
    editStockItem: "Modifier l'article",
    editClient: 'Modifier le client',
    addNewClient: 'Ajouter un nouveau client',
    editSupplier: 'Modifier le fournisseur',
    editEmployee: "Modifier l'employé",
    addNewEmployee: 'Ajouter un nouvel employé',
    editExpense: 'Modifier la dépense',
    editSale: 'Modifier la vente',
    editProduct: 'Modifier le produit',
    createProductTitle: 'Créer un produit',

    // Form labels
    itemName: "Nom de l'article",
    selectCategory: 'Sélectionner la catégorie',
    selectSupplier: 'Sélectionner le fournisseur (optionnel)',
    currentQuantity: 'Quantité actuelle',
    initialQuantity: 'Quantité initiale',
    costPerUnit: 'Coût unitaire (DZD)',
    lowStockAlertThreshold: 'Seuil d\'alerte stock bas',
    alertWhenBelow: 'Alerte quand la quantité descend en dessous',
    useStockAdjustments: 'Utilisez les ajustements pour modifier la quantité',
    additionalNotes: 'Notes supplémentaires...',
    update: 'Mettre à jour',
    clientName: 'Nom du client',
    optional: 'optionnel',
    initialBalance: 'Solde initial (DZD)',
    amountOwed: 'Montant dû par le client',
    selectClient: 'Sélectionner un client',
    saleDate: 'Date de vente',
    selectProduct: 'Sélectionner le produit',
    qty: 'Qté',
    addItem: 'Ajouter un article',
    summary: 'Résumé',
    subtotal: 'Sous-total',
    paidAmount: 'Montant payé',
    amountPaidNow: 'Montant payé maintenant',
    createSale: 'Créer la vente',
    hireDate: "Date d'embauche",
    monthlySalaryAmount: 'Salaire mensuel (DZD)',
    employeeIsActive: "L'employé est actif",
    expenseCategory: 'Catégorie de dépense',
    expenseAmount: 'Montant (DZD)',
    expenseDate: 'Date',
    isRecurring: 'Dépense récurrente',
    recurringPeriod: 'Période de récurrence',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    quarterly: 'Trimestriel',
    yearly: 'Annuel',
    manualCostPerUnit: 'Coût unitaire manuel (DZD)',
    overrideRecipeCost: 'Remplacer le calcul de la recette',
    recipeIngredients: 'Recette / Ingrédients',
    ingredientsList: 'Définir les ingrédients par unité',
    selectIngredient: "Sélectionner l'ingrédient",
    amountNeeded: 'Quantité nécessaire',
    addIngredient: 'Ajouter un ingrédient',
    noIngredientsAdded: 'Aucun ingrédient ajouté',
    calculatedCost: 'Coût calculé',
    perUnit: 'par unité',
    addIngredientsToCalculate: 'Ajoutez des ingrédients pour calculer',

    // Validation messages
    nameRequired: 'Le nom est requis',
    mustBeValidNumber: 'Doit être un nombre valide',
    invalidEmailFormat: "Format d'e-mail invalide",
    categoryRequired: 'La catégorie est requise',
    validAmountRequired: 'Un montant valide est requis',
    dateRequired: 'La date est requise',
    selectRecurringPeriod: 'Sélectionnez la période de récurrence',
    hireDateRequired: "La date d'embauche est requise",
    pleaseSelectClient: 'Veuillez sélectionner un client',
    addAtLeastOneProduct: 'Ajoutez au moins un produit',
    allItemsMustHaveDetails: 'Tous les articles doivent avoir un produit, une quantité et un prix',
    supplierName: 'Nom du fournisseur',
    currentBalance: 'Solde actuel (DZD)',
    youOweSupplier: 'Positif = vous devez au fournisseur, Négatif = le fournisseur vous doit',
    fullName: 'Nom complet',
    rolePosition: 'Rôle / Poste',
    addEmployeeBtn: 'Ajouter un employé',
    daily: 'Quotidien',
    selectPeriod: 'Sélectionner la période',
    saleDetails: 'Détails de la vente',
    payment: 'Paiement',
    amountPaidDZD: 'Montant payé (DZD)',
    addProduct: 'Ajouter un produit',
    selectProductPlaceholder: 'Sélectionner le produit...',
    selectClientPlaceholder: 'Sélectionner le client...',
    noProductsAdded: 'Aucun produit ajouté',
    clickAddProduct: 'Cliquez sur "Ajouter un produit" pour ajouter des articles',
    orderNotes: 'Notes de commande...',
    productDetails: 'Détails du produit',
    sellingPriceDZD: 'Prix de vente (DZD)',
    manualCostOptional: 'Coût manuel (optionnel)',
    unitPieces: 'Pièces (pcs)',
    unitKilogram: 'Kilogramme (kg)',
    unitBox: 'Boîte',
    unitPack: 'Paquet',
    selectIngredientPlaceholder: "Sélectionner l'ingrédient...",
    noIngredientsYet: 'Aucun ingrédient ajouté',
    clickAddIngredientHint: 'Cliquez sur "Ajouter un ingrédient" pour créer la recette',
    calculatedIngredientCost: 'Coût des ingrédients calculé',
    profitMargin: 'Marge bénéficiaire',
    autoCalculate: 'Calcul automatique',
    available: 'disponible',

    // Documents & Reports
    documents: 'Documents',
    documentsReports: 'Documents et rapports',
    generateDocuments: 'Générer des factures, bons de livraison et rapports',
    documentPrefixes: 'Préfixes des documents',
    invoicePrefix: 'Préfixe facture',
    deliveryNotePrefix: 'Préfixe bon de livraison',
    proformaPrefix: 'Préfixe proforma',
    salesDocsDesc: 'Factures, bons de livraison, proformas',
    reportsDesc: 'Rapports stock, ventes, clients, dépenses',
    invoices: 'Factures',
    deliveryNotes: 'Bons de livraison',
    salesDocuments: 'Documents de vente',
    businessReports: "Rapports d'activité",
    invoice: 'Facture',
    invoiceDesc: 'Document de facturation officiel',
    deliveryNote: 'Bon de livraison',
    deliveryNoteDesc: 'Preuve de livraison des marchandises',
    proformaInvoice: 'Facture proforma',
    proformaInvoiceDesc: 'Devis avant confirmation de vente',
    proformaDesc: 'Facture préliminaire avant facturation définitive',
    purchaseOrder: 'Bon de Commande',
    purchaseOrderDesc: 'Commande client avant livraison',
    exitVoucher: 'Bon de Sortie',
    exitVoucherDesc: 'Registre de retrait de stock interne',
    creditNote: 'Avoir',
    creditNoteDesc: 'Retours et remboursements',
    quoteEstimate: 'Devis',
    quoteEstimateDesc: 'Tarification formelle pour les clients',
    receptionVoucher: 'Bon de Réception',
    receptionVoucherDesc: 'Marchandises reçues du fournisseur',
    monthlySummary: 'Récapitulatif Mensuel',
    monthlySummaryDesc: 'Aperçu des ventes, dépenses et bénéfices',
    productSheet: 'Fiche Produit',
    productSheetDesc: 'Catalogue produits avec détails',
    productionReport: 'Rapport de Production',
    productionReportDesc: 'Historique des lots de production et coûts',
    selectDocumentType: 'Sélectionner le Type de Document',
    whatDocumentGenerate: 'Quel document souhaitez-vous générer ?',
    skipDocument: 'Passer',
    documentCenter: 'Centre de Documents',
    conditionsGenerales: 'Conditions Générales de Vente',
    validUntil: 'Valable Jusqu\'au',
    deliveryDate: 'Date de Livraison Prévue',
    paymentConditions: 'Conditions de Paiement',
    originalInvoice: 'Facture Originale',
    returnReason: 'Motif de Retour',
    authorizedBy: 'Autorisé Par',
    warehouseLocation: 'Emplacement Entrepôt',
    receivedBy: 'Réceptionné Par',
    qualityCheck: 'Contrôle Qualité',
    supplierInfo: 'Informations Fournisseur',
    batchDetails: 'Détails du Lot',
    ingredientCost: 'Coût des Ingrédients',
    yieldQuantity: 'Quantité Produite',
    stockReport: 'Rapport de stock',
    stockReportDesc: 'Niveaux et valeurs actuels du stock',
    salesReport: 'Rapport des ventes',
    salesReportDesc: 'Résumé des ventes par période',
    clientStatement: 'Relevé client',
    clientStatementDesc: 'Dettes et historique des paiements',
    expenseReport: 'Rapport des dépenses',
    expenseReportDesc: 'Résumé des dépenses par catégorie',
    recentDocuments: 'Documents récents',
    noDocumentsYet: 'Aucun document généré',
    generateFirstDocument: 'Générez votre premier document à partir d\'une vente',
    companySettings: "Paramètres de l'entreprise",
    companyInfo: "Informations de l'entreprise",
    legalInfo: 'Informations légales',
    businessNameAr: "Nom de l'entreprise (Arabe)",
    businessNameFr: "Nom de l'entreprise (Français)",
    businessAddress: "Adresse de l'entreprise",
    businessPhone: "Téléphone de l'entreprise",
    businessEmail: "E-mail de l'entreprise",
    nif: 'NIF (Numéro d\'Identification Fiscale)',
    rc: 'RC (Registre du Commerce)',
    ai: "AI (Article d'Imposition)",
    nis: 'NIS (Numéro d\'Identification Statistique)',
    rib: 'RIB (Relevé d\'Identité Bancaire)',
    tvaRate: 'Taux TVA (%)',
    saveSettings: 'Enregistrer les paramètres',
    settingsSaved: 'Paramètres enregistrés avec succès',
    generateDocument: 'Générer un document',
    generateInvoice: 'Générer une facture',
    generateDeliveryNote: 'Générer un bon de livraison',
    generateProforma: 'Générer une proforma',
    printDocument: 'Imprimer le document',
    printReport: 'Imprimer le rapport',
    generateReport: 'Générer un rapport',
    reportSummary: 'Résumé du rapport',
    back: 'Retour',
    downloadPdf: 'Télécharger PDF',
    documentNumber: 'Numéro du document',
    documentDate: 'Date du document',
    selectSale: 'Sélectionner une vente',
    selectDateRange: 'Sélectionner la période',
    fromDate: 'Du',
    toDate: 'Au',
    preview: 'Aperçu',
    print: 'Imprimer',
    close: 'Fermer',

    // POS (Point of Sale)
    pos: 'Point de vente',
    pointOfSale: 'Vente rapide avec scan de code-barres',
    scanBarcode: 'Scanner le code-barres ou saisir le code...',
    cart: 'Panier',
    cartEmpty: 'Panier vide',
    scanOrSelectProducts: 'Scannez ou sélectionnez des produits',
    addedToCart: 'ajouté au panier',
    productNotFound: 'Produit non trouvé',
    multipleProductsFound: 'Plusieurs produits trouvés',
    scanError: 'Erreur de scan',
    confirmClearCart: 'Vider le panier ?',
    walkInCustomer: 'Client de passage',
    noPhone: 'Pas de téléphone',
    paymentMethod: 'Mode de paiement',
    cash: 'Espèces',
    credit: 'Crédit',
    exactAmount: 'Exact',
    change: 'Monnaie',
    completeSale: 'Finaliser la vente',
    saleCompleted: 'Vente effectuée avec succès !',
    saleError: 'Erreur lors de la vente',
    generateDocumentQuestion: 'Générer une facture pour cette vente ?',
    favorites: 'Favoris',
    keyboardShortcuts: 'Raccourcis clavier',
    focusBarcodeScanner: 'Focus sur le scanner',
    focusProductSearch: 'Focus sur la recherche',
    toggleFavorites: 'Basculer les favoris',
    openPayment: 'Ouvrir le paiement',
    clearCart: 'Vider le panier',
    closeModal: 'Fermer la fenêtre',
    errorLoadingData: 'Erreur de chargement des données',
    pay: 'Payer',

    // Theme
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    appearance: 'Apparence',

    // Language
    language: 'Langue',
    english: 'Anglais',
    arabic: 'Arabe',
    french: 'Français',

    // Months
    january: 'Janvier',
    february: 'Février',
    march: 'Mars',
    april: 'Avril',
    may: 'Mai',
    june: 'Juin',
    july: 'Juillet',
    august: 'Août',
    september: 'Septembre',
    october: 'Octobre',
    november: 'Novembre',
    december: 'Décembre',

    // Sales History
    salesHistory: 'Historique des ventes',
    today: "Aujourd'hui",
    thisWeek: 'Cette semaine',
    customRange: 'Période personnalisée',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    apply: 'Appliquer',
    transactions: 'Transactions',
    totalPaid: 'Total payé',
    noSalesFound: 'Aucune vente trouvée',
    tryDifferentDateRange: 'Essayez une autre période',
    filterByDate: 'Filtrer par date',
    allTime: 'Tout le temps',

    // Authentication
    login: 'Connexion',
    logout: 'Déconnexion',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    incorrectCredentials: "Nom d'utilisateur ou mot de passe incorrect",
    loginToAccount: 'Connectez-vous à votre compte',
    enterCredentials: 'Entrez vos identifiants pour accéder au système',
    loggingIn: 'Connexion en cours...',
    welcomeUser: 'Bienvenue',
    logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter ?',

    // User Management
    userManagement: 'Gestion des utilisateurs',
    addUser: 'Ajouter un utilisateur',
    editUser: "Modifier l'utilisateur",
    deleteUser: "Supprimer l'utilisateur",
    users: 'Utilisateurs',
    admin: 'Administrateur',
    manager: 'Responsable',
    salesRole: 'Ventes',
    userRole: 'Rôle',
    lastLogin: 'Dernière connexion',
    neverLoggedIn: 'Jamais',
    userCreated: 'Utilisateur créé avec succès',
    userUpdated: 'Utilisateur mis à jour avec succès',
    userDeleted: 'Utilisateur supprimé avec succès',
    confirmDeleteUser: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    cannotDeleteSelf: 'Vous ne pouvez pas supprimer votre propre compte',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    usernameRequired: "Le nom d'utilisateur est requis",
    passwordRequired: 'Le mot de passe est requis',
    leaveBlankPassword: 'Laissez vide pour garder le mot de passe actuel',

    // System Reset
    systemReset: 'Réinitialisation du système',
    resetSystem: 'Réinitialiser le système',
    resetWarning: 'Attention : Cela supprimera toutes les données définitivement !',
    resetDescription: 'Cette action effacera toutes les ventes, le stock, les clients, les fournisseurs, les dépenses et autres données. Seuls les comptes utilisateurs et les paramètres seront conservés.',
    confirmReset: 'Tapez votre mot de passe pour confirmer',
    resetSuccess: 'Le système a été réinitialisé avec succès',
    resetError: 'Erreur lors de la réinitialisation',
    dataCleared: 'Toutes les données ont été effacées',
    irreversibleAction: 'Cette action est irréversible !',

    // Resale Products
    resaleProducts: 'Produits de revente',
    resaleProduct: 'Produit de revente',
    addResaleProduct: 'Ajouter un produit de revente',
    editResaleProduct: 'Modifier le produit de revente',
    purchasePrice: "Prix d'achat",
    barcode: 'Code-barres',
    sku: 'Référence',
    inStock: 'En stock',
    reorderLevel: 'Seuil de réapprovisionnement',
    resale: 'Revente',
    manufactured: 'Fabriqué',
    productType: 'Type de produit',
    searchResaleProducts: 'Rechercher des produits de revente...',
    noResaleProductsYet: 'Aucun produit de revente',
    addFirstResaleProduct: 'Ajoutez votre premier produit de revente',

    // Settings Page
    generalSettings: 'Paramètres généraux',
    securitySettings: 'Paramètres de sécurité',
    dangerZone: 'Zone de danger',
    businessSettings: "Paramètres de l'activité",
    systemSettings: 'Paramètres système',

    // Resale/Inventory additions
    resaleProductDesc: 'Achat et vente directe sans production',
    purchasePriceDZD: "Prix d'achat (DZD)",
    resaleProductNote: 'Produit de revente',
    resaleProductInfo: 'Ce produit sera acheté et vendu directement. Utilisez "Ajouter stock" dans la page inventaire pour ajouter des quantités.',
    profitPerUnit: 'Profit par unité',
    resaleStockPurchase: 'Achat de stock de revente',
    currentStock: 'Stock actuel',
    quantityToAdd: 'Quantité à ajouter',
    unitCostDZD: 'Coût unitaire (DZD)',
    purchaseNotes: 'Notes d\'achat...',
    discount: 'Remise',

    // Payroll additions
    payrollDescription: 'Cela créera des fiches de paie pour tous les employés actifs du mois sélectionné.',
    payrollSkipWarning: 'Les employés ayant déjà une fiche de paie pour ce mois seront ignorés.',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('dir', 'ltr');
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : prev === 'ar' ? 'fr' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
